In [7]:
import seaborn as sns
df=sns.load_dataset('tips')

In [9]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [13]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [18]:
## featue encoding(Label Encoding and One Hot Encoding)

In [19]:
from sklearn.preprocessing import LabelEncoder

In [30]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [21]:
## indepenedent and Deprndent feature

In [22]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [44]:
x=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y=df['total_bill']

In [70]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)

In [71]:
x_train.head()

      tip   sex smoker  day    time  size
234  3.00  Male    Yes  Sat  Dinner     2
227  3.00  Male     No  Sat  Dinner     4
180  3.68  Male    Yes  Sun  Dinner     4
5    4.71  Male     No  Sun  Dinner     4
56   3.00  Male    Yes  Sat  Dinner     4

In [72]:

x_train['sex']=le1.fit_transform(x_train['sex'])
x_train['smoker']=le2.fit_transform(x_train['smoker'])
x_train['time']=le3.fit_transform(x_train['time'])

In [73]:
x_train.head()

      tip  sex  smoker  day  time  size
234  3.00    1       1  Sat     0     2
227  3.00    1       0  Sat     0     4
180  3.68    1       1  Sun     0     4
5    4.71    1       0  Sun     0     4
56   3.00    1       1  Sat     0     4

In [74]:
x_test['sex'] = le1.transform(x_test['sex'])       # Transforms 'sex' column
x_test['smoker'] = le2.transform(x_test['smoker']) # Transforms 'smoker' column
x_test['time'] = le3.transform(x_test['time'])     # Transforms 'time' column

In [75]:
x_test.columns

Index(['tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [76]:
## One Hot Encoding -- column Transformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [77]:
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[3])],remainder='passthrough')

In [78]:
x_train=ct.fit_transform(x_train)

In [79]:
x_test=ct.transform(x_test)

In [80]:
x_test

array([[1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 3.92, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.45, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 6.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 1.44, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.75, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.55, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.67, 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 1.61, 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.72, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.03, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 4.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 4.5 , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.03, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 5.15, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.75, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.74, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.14, 0.  , 0.  , 0.  , 5.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 5.65, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 2.5 , 0.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.01, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 4.08, 0.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.09, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 3.41, 1.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 3.48, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 5.  ],
       [0.  , 0.  , 1.  , 2.71, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 3.  , 0.  , 0.  , 0.  , 2.  ]])

In [81]:
### Apply support vector regressor
###SVR

from sklearn.svm import SVR
svr=SVR()

svr.fit(x_train,y_train)

In [83]:
y_pred=svr.predict(x_test)

In [84]:
from sklearn.metrics import r2_score,mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.496241694353699
4.175959078886017

In [85]:
y_pred

array([17.29817835, 14.44316543, 19.08482736, 27.81171877, 13.76497288,
       15.12775863, 15.29560601, 14.46994309, 17.82231704, 16.87090037,
       17.07062749, 13.08950849, 12.60529636, 15.12775863, 12.67729756,
       14.26693057, 21.88958837, 20.19771537, 15.01532731, 27.44429646,
       19.80590834, 20.14873394, 20.47281611, 13.06913355, 21.18325617,
       14.15635532, 13.9541114 , 23.61405744, 19.08482736, 27.50777455,
       22.68388103, 13.69108447, 19.5319204 , 17.88949595, 20.83583833,
       20.4404197 , 13.65208944, 26.30430434, 15.11341024, 14.53273551,
       12.90750074, 13.29668771, 15.73308163, 15.67579728, 14.06648371,
       13.08497553, 13.7885589 , 16.71465308, 12.75325599, 15.76744732,
       14.59276898, 20.51220173, 26.21768814, 13.56175737, 18.77523034,
       13.50570119, 24.07581075, 13.45451285, 18.40535462, 19.42105983,
       28.19260314, 18.61115242, 25.09666279, 14.78330685, 13.92339752,
       20.54334313, 14.71712968, 12.66170931, 20.81096476, 20.87785105,
       19.08482736, 23.86435751, 15.20719584, 16.64567129])